config/routes.rb
Rails.application.routes.draw do
 
  get 'tasks', to:'tasks#index'
  resources :tasks, except: [:index]
 
  root 'chatroom#index'
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  get 'signup', to: 'users#new'
  resources :users, except: [:new ]
  
  delete 'logout', to: 'sessions#destroy'
  get 'logout', to: 'sessions#destroy'


  get 'users', to: 'users#index'
  resources :users

  resources :categories
  get 'categories', to: 'categories#new'
  namespace :api do
    namespace :v1 do
      resources :tasks, only: [:index, :show, :create, :destroy, :update]
      resources :categories, only: [:index, :show, :create, :destroy, :update]
      resources :sessions
      resources :users, only: [:index, :show, :create, :destroy, :update]
    end
  end
end

app/models/category.rb
class Category < ApplicationRecord
    validates :category, presence: true 
    has_many :tasks
    validates_uniqueness_of :category
end

app/controllers/api/v1/categories_controller.rb
module Api
    module V1
        class CategoriesController < ApplicationController
            before_action :set_category, only: %i[ show edit update destroy ]
        
           
            def index
            @categories = Category.all
            render json: @categories
            end
        
    
            def show
            render json: @category           
            end
        
            def new
            @category = Category.new
            end
        
       
            def edit
            end
            def create
                @category = Category.new(category_params)
            
                if @category.save
                  render json: @category, status: :created, location: @category
                else
                  render json: @category.errors, status: :unprocessable_entity
                end
            end
        

        
         
            def update
            respond_to do |format|
                if @category.update(category_params)
                format.html { redirect_to category_url(@category), notice: "Category was successfully updated." }
                format.json { render :show, status: :ok, location: @category }
                else
                format.html { render :edit, status: :unprocessable_entity }
                format.json { render json: @category.errors, status: :unprocessable_entity }
                end
            end
            end
       
            def destroy
            @category.destroy
        
            respond_to do |format|
                format.html { redirect_to categories_url, notice: "Category was successfully destroyed." }
                format.json { head :no_content }
            end
            end
        
            private
       
            def set_category
                @category = Category.find(params[:id])
            end
        
        
            def category_params
            params.require(:category).permit(:category)
            end
        end
    end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: %i[ show edit update destroy ]
  def index
    @categories = Category.all
  end
  def show
    @tasks = Task.where(user_id: current_user,category_id: params[:id] )
    p @tasks
  end
  def new
    @category = Category.new
  end

  def edit
  end

  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to category_url(@category), notice: "Category was successfully created." }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to category_url(@category), notice: "Category was successfully updated." }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end
  def destroy
    @category.destroy

    respond_to do |format|
      format.html { redirect_to categories_url, notice: "Category was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
  
    def set_category
      @category = Category.find(params[:id])
    end

    def category_params
      params.require(:category).permit(:category)
    end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_form.html.erb
<%= form_with(model: category) do |form| %>
  <% if category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
        <% category.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :category %>
    <%= form.text_field :category %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<h1>Editing Category</h1>

<%= render 'form', category: @category %>

<%= link_to 'Show', @category %> |
<%= link_to 'Back', categories_path %>

app/views/categories/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Categories</h1>

<table>
  <thead>
    <tr>
      <th><h2>Category</h2></th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @categories.each do |category| %>
      <tr>
        <td><h2><%= category.category %></h2></td>
        <td><h2><%= link_to 'Show', category %></h2></td>
        <td><h2><%= link_to 'Edit', edit_category_path(category) %></h2></td>
        <td><h2><%= button_to 'Destroy', category, method: :delete, data: { confirm: 'Are you sure?' } %></h2></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<h2>
<%= link_to 'New Category', new_category_path %></h2>

app/views/categories/new.html.erb
<h1>New Category</h1>

<%= render 'form', category: @category %>

<%= link_to 'Back', categories_path %>

app/views/categories/show.html.erb
<p id="notice"><%= notice %></p>


<h1>To-Do List</h1>



<table border="1">
  <thead>
    <tr>
      <th><h2>Task Name</h2></th>
      <th><h2>Done/Not</h2></th>
      <th colspan="4"> <h2>Actions</h2></th>
    </tr>
  </thead>

  <tbody>
    <% @tasks.each do |task| %>
      <tr>
        <td><h2><%= task.name%></h2></td>
        <td><h2><%= task.status %></h2></td>
        <td><%= link_to 'Show', task,class: 'btn' %></td>
        <td><%= link_to 'Edit', edit_task_path(task),class: 'btn' %></td>
        <td><%= button_to 'Destroy', task, method: :delete, data: { confirm: 'Are you sure?' },class: 'btn'%></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<h2><%= link_to 'New Task', new_task_path %></h2>