config/routes.rb
Rails.application.routes.draw do
 
  get 'tasks', to:'tasks#index'
  resources :tasks, except: [:index]
 
  root 'chatroom#index'
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  get 'signup', to: 'users#new'
  resources :users, except: [:new ]
  
  delete 'logout', to: 'sessions#destroy'
  get 'logout', to: 'sessions#destroy'


  get 'users', to: 'users#index'
  resources :users

  resources :categories
  get 'categories', to: 'categories#new'
  namespace :api do
    namespace :v1 do
      resources :tasks, only: [:index, :show, :create, :destroy, :update]
      resources :categories, only: [:index, :show, :create, :destroy, :update]
      resources :sessions
      resources :users, only: [:index, :show, :create, :destroy, :update]
    end
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>To-do app</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= favicon_link_tag asset_path('icon.png') %>


   <style>
   
  </style>


  </head>

  <body>
     
<div class="ui inverted menu">
<div class="ui container">
<% if logged_in? %>
<div class="item">
<div class="ui primary button"><%= link_to 'Create Categories', categories_path %></div>
<div class="ui secondary button"><%= link_to 'Go to all tasks', tasks_path %></div>

</div>

<div class="right menu">
  <div class="item">
  <div class="ui primary button" ><%= link_to 'Log Out', logout_path, method: :delete%></div>
  </div>
</div>
<% else %>
<div class="right menu">
<div class="item">
      <div class="ui primary button"><%= link_to 'Sign Up', signup_path %></div>
  </div>
  <div class="item">
   
      <div class="ui primary button"><%= link_to 'Log in', login_path %></div>
  </div>
  </div>
<% end %>
</div>
</div>
    <div class="ui container">
    <%= yield %>
  </div>
  </body>
</html>